/**
 * App-Secret Generator for Webhook Authentication
 * 
 * Generates time-based SHA256 hash for App-Secret header.
 * The secret is generated by hashing: SHA256('{ADMIN_API_KEY}-{current_minute_timestamp}')
 * 
 * This matches the validation logic in the Next.js application which validates
 * against current minute ±2 minutes for clock skew tolerance.
 */

import * as crypto from 'crypto';

/**
 * Generate App-Secret header value
 * Creates a time-based SHA256 hash using the admin API key and current minute timestamp
 * 
 * @param adminApiKey - The ADMIN_API_KEY from environment
 * @returns The generated App-Secret hash string
 */
export function generateAppSecretHeader(adminApiKey: string): string {
  if (!adminApiKey) {
    console.warn('[AppSecretGenerator] ADMIN_API_KEY not configured, App-Secret header will be empty');
    return '';
  }

  // Get current timestamp in minutes (Unix epoch) - MUST match Next.js validation
  // Next.js uses: Math.floor(Date.now() / 1000 / 60)
  const timestampToMinute = Math.floor(Date.now() / 1000 / 60);
  
  // Create the secret string: '{ADMIN_API_KEY}-{timestamp}'
  const secretString = `${adminApiKey}-${timestampToMinute}`;
  
  // Generate SHA256 hash
  const hash = crypto.createHash('sha256').update(secretString).digest('hex');
  
  console.log(`[AppSecretGenerator] Generated App-Secret for minute timestamp: ${timestampToMinute}`);
  
  return hash;
}

/**
 * Check if App-Secret authentication is configured
 * 
 * @param adminApiKey - The ADMIN_API_KEY from environment
 * @returns true if adminApiKey is provided and non-empty
 */
export function isAppSecretConfigured(adminApiKey: string | undefined): boolean {
  return !!adminApiKey && adminApiKey.trim().length > 0;
}

/**
 * Generate webhook signature (HMAC-SHA256)
 * Used for x-webhook-signature header validation on the Next.js side
 * 
 * @param payload - The raw JSON payload string
 * @param secret - The AZURE_WEBHOOK_SECRET
 * @returns The HMAC-SHA256 signature as hex string
 */
export function generateWebhookSignature(payload: string, secret: string): string {
  if (!secret) {
    console.warn('[WebhookSignature] AZURE_WEBHOOK_SECRET not configured');
    return '';
  }

  const hmac = crypto.createHmac('sha256', secret);
  hmac.update(payload);
  const signature = hmac.digest('hex');
  
  console.log(`[WebhookSignature] Generated HMAC-SHA256 signature for payload`);
  
  return signature;
}

/**
 * Check if webhook signature is configured
 * 
 * @param webhookSecret - The AZURE_WEBHOOK_SECRET from environment
 * @returns true if webhookSecret is provided and non-empty
 */
export function isWebhookSignatureConfigured(webhookSecret: string | undefined): boolean {
  return !!webhookSecret && webhookSecret.trim().length > 0;
}
